apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickandmorty-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rickandmorty
  template:
    metadata:
      labels:
        app: rickandmorty
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: rickandmorty
          image: caravem/rickandmorty:64e08fa9addf66b7684278bea9a70da613ddc9bf
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mongo-secret
 