apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: develop
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:admin@mongodb-service.mongodb.svc.cluster.local:27017/admin"
  MONGO_DB_NAME: "rickandmorty"
  URL_RICK_AND_MORTY: "https://rickandmortyapi.com/api/character"
  PORT: "3000"